### ISSUE TITLE
Instructor Razuvious targets Priest when taunt falls off

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#100]
Situation was as follows:

Two priests doing MC.

1. Priest 1 (Kalsi) is first to do MC and puts Raz into tanking position.
2. Priest 2 (Atrea) MC another add and tanks. Uses Taunt on Razuvious.
3. Atrea uses Taunt
4. Taunt Falls off Razuvious
5. Razuvious goes on Priest 1 and one-shots him.

Correct behaviour should obviously be that Razuvious keeps attacking the add that just taunted him and not go on anyone else. 

Video where you can see it happening:https://www.youtube.com/watch?v=EvDmeGZhF20

**Comment by gemt** [comment]
Noticed it as well yesterday. The MCed adds threat is somehow not properly taken into consideration on razuvs threatlist. Looking into it.

**Comment by gemt** [comment]
Fixed with 1.11 Taunt mechanic changes ;)
