### ISSUE TITLE
Sapphiron Ice Block cast after Frost Bomb

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#101]
During one of the air phases tonight we only got 4 ice blocks followed by the frost bomb. Then just as he landed he hit one of our players with the last fifth ice block.

Correct behaviour is to have all five ice blocks hit before the frost bomb is cast.

**Comment by gemt** [comment]
vod of the entire airphase if possible

**Comment by kevmodrome** [comment]
VoD: https://www.youtube.com/watch?v=RUqdPmuWOqM

**Comment by gemt** [comment]
Made some minor tweaks to it, though the iceblock spell has a delay on spawning the iceblock so it may sometimes appear as if he starts casting bomb and last iceblock nearly at the same time.
