### ISSUE TITLE
Gothik Trainees not currently crowd-controllable - should be

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#102]
The trainees on the living side can't be sheeped or feared. This was a thing back in vanilla.

Source: https://youtu.be/FN2QtHx8_xw?t=2m21s (look at the star mark for example)

**Comment by kevmodrome** [comment]
And here is a source showing them being fearable: https://youtu.be/S6nzYNx8RU0?t=3m12s

**Comment by gemt** [comment]
They are actually susceptible to these forms of CC already, but some of the sql changes were missing the first day or so on the PTR. Thanks for report anyhow!
