### ISSUE TITLE
Sapphiron currently hit by regular auto attack when in the air - should not be

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#103]
Looking at some old Sapphiron video you can see normal melee attacks not working on Sapphiron when he is in the air. "Yellow" attacks seem to be working though.

Source: https://www.youtube.com/watch?v=Y1pDvjCISV4 (6:00 mark, other side of the room you see a rogue doing one attack and nothing else, etc)

**Comment by gemt** [comment]
Fixed
