### ISSUE TITLE
Uppercut skill on trash before Grobbulus range is too big

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#107]
Looking at the video here you can see the tank pull the three mobs back and at 0:06 you will see him fly up in the air even though he is far away from the mobs.

VoD: https://www.youtube.com/watch?v=G-CxZ7z8Jt8

**Comment by gemt** [comment]
Struggled figuring out the abilities for these mobs.

I did not find any relevant spells named "Uppercut" or anything similar, the assumed ability is a ranged spell, that on the first ptr session was used on a random target. After the reports from previous session I changed it to be on current tank only, which made sense with respect to the "uppercut" ability. However, this is a ranged spell, so if its the correct one there is no reason he cant use it from ranged. A possibly more correct behaviour is changing the timer of the spell, but cant know without some videos from retail.

**Comment by gemt** [comment]
Fixed
