### ISSUE TITLE
Heigan Aggro Range

### ISSUE THREAD

**Issue by eazyotto** [elysium-project/naxxramas_ptr_feedback#108]
The Range on which Heigan would get aggro´d is way to low, the whole point of the suppression room would be wasted, when u can prepare for the fight inside his room.

Right when u run around the corner (still outside of his gate) you would add him.
You shouldnt be able to rezz up inside of his room for example, which makes Soulstones & Battlerezzes useless.

Just expand his Aggrorange a bit plz.

Proof: https://www.youtube.com/watch?v=w8_fRIOOsMk

**Comment by gemt** [comment]
Counter proof:
https://www.youtube.com/watch?v=kCnk6lwi2ug
https://www.youtube.com/watch?v=0hwEW57-jw8
https://www.youtube.com/watch?v=ZchSCteUups

It was changed after release on retail. Will probably update it, but you may not know until release!
