### ISSUE TITLE
Corpse Scarab deal to much damage.

### ISSUE THREAD

**Issue by eazyotto** [elysium-project/naxxramas_ptr_feedback#11]
Compared to my vanilla Exp the Corpse Scarabs shouldnt deal as much damage. They hit for 1.5k per hit on a paladin Healer, with good amount of armor.

**Comment by Pleasant-Elysium** [comment]
Sources please!

**Comment by blubba22** [comment]
Difficult to provide sources unfortunately. In this video from on of our guild mates from vanilla, you can see that even warlocks used hellfire to kill them, which would be suicide if they hit as hard back then.

https://www.youtube.com/watch?v=x-Irir7we24 (3:55, unfortunately you can't see exactly for how much they are hitting and the recording player always moves in such a way that you can't see them handle the scarabs clearly).

http://wowwiki.wikia.com/wiki/Anub%27Rekhan_(original) says they hit for 400. But I guess it's not a reliable source.

**Comment by ettern** [comment]
They should hit a cloth user for 200-300ish.
[https://youtu.be/6JHmguxPN14?t=6m34s](https://youtu.be/6JHmguxPN14?t=6m34s)

**Comment by gemt** [comment]
Fix is pushed to hit. Not yet live.
