### ISSUE TITLE
Some Trash Mob Info (Placement + Models)

### ISSUE THREAD

**Issue by Zoldam** [elysium-project/naxxramas_ptr_feedback#110]
First up, I want to say AMAZING job with the trash mobs, a lot of servers just use the Wrath placement with the vanilla mobs which is totally wrong, it was wonderful to see the correct mobs and placement. But to add to that, I did notice a couple things that were off. This is nitpicking, but I know you are going for 100% authentic, so please don't take it like I am bashing the work so far.

Let me give a brief history behind this. A couple years ago I aided one of the devs on a vanilla server that didn't last long due to host funding issues, it was called Twilight-Realms or something like that. What I aided them with, was trash mob placement, patrols, etc. due to this I also worked on Naxxramas as well. I poured through a minimum of 40 videos (not easy when the videos were vanilla/BC age) and payed OCD level of detail to even the most minor things

While I noticed minor things here and there (mob scaling being off be several percent, locations of by about half a yard, etc.) I did notice a couple note-worthy ones...

The first is that in the tunnel before Grand Widow, the giant green spiders patrolling are Venom Stalkers, they should be their Outer Ring variant Necro Stalker, this is the only time the Outer Ring variant of a mob appears somewhere outside of the Outer Ring. I remember this well because there is a quest to kill 3 Venom Stalkers, and the only 3 that give credit were the ones prior to Anub'Rekhan, and I remember finding an older video that confirmed it.

Second, the Spirits and Shades of Naxxramas do not seem to have stealth detect, I am not sure if this is intentional for the PTR or not.

Third is that a few mobs use models that are in the database, but were never actually used in retail. An example would be the Deathknight Captains with grey/silver hair (instead of orange/red) or female acolytes (retail only spawned male acolytes).

If anyone in the team is interested, I can do a more in-depth look with more detailed issues I find, and also give out my Naxxramas records from when I worked on it.

**Comment by gemt** [comment]
PM me on discord and we can set something up, thanks a lot for this!
