### ISSUE TITLE
Instructor Razuvious: Not dropping aggro when player uses Limited Invulnerability Potion

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/naxxramas_ptr_feedback#111]
# Scuba Cops PTR Test Feedback

### Issue - Not dropping aggro when player uses Limited Invulnerability Potion

We had a player use a Limited Invulnerability Potion (http://db.vanillagaming.org/?item=3387) and Razuvious did not change his target as mobs are supposed to do when a player consumes this item.

**Comment by gemt** [comment]
Works for me locally. I fixed some other things on him that could be the reason  lips were not working
