### ISSUE TITLE
Gothik: Spawning mobs stand still and do not aggro on players if no one is in their aggro range.

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/naxxramas_ptr_feedback#112]
# Scuba Cops PTR Test Feedback

### Issue - Spawning mobs stand still and do not aggro on players if no one is in their aggro range.

The mobs should actively seek out a player to attack when they spawn. Fix would be potentially making those mobs have a 100 yard aggro range?

PTR: https://youtu.be/Z_CI77ETXW0?t=874

**Comment by gemt** [comment]
Can I get a confirmation about weather or not this was working as intended after the sunday update?

**Comment by gemt** [comment]
Seems it's been fixed
