### ISSUE TITLE
Can't intercept if you are knocked in the air by the Stitched Spewers

### ISSUE THREAD

**Issue by BrynjaDarrow** [elysium-project/naxxramas_ptr_feedback#113]
Back in the day, you were able to intercept as a warrior when you get knocked in the air by the Stitched Spewers. This would negate all fall damage.

This is more of a general bug, since the same was possible if you get knocked away by Ragnaros for example and isn't on this server. Would be great if this could be fixed.

**Comment by gemt** [comment]
Its a general bug yea. Would be better to report this in the regular development repo here: 
https://github.com/elysium-project/server/issues
