### ISSUE TITLE
Stalagg & Feugen are immune to taunt (Thaddius fight)

### ISSUE THREAD

**Issue by vindruvor** [elysium-project/naxxramas_ptr_feedback#114]
As you can see on the screenshot below; Feugen is immune to taunt.

http://imgur.com/a/rdAu8

A guildie tried taunting Stalagg as well and he was also immune according to him.

According to wowwiki (vanilla) they should both be vulnerable to taunt (i.e tauntable). 
Wowwiki link: http://wowwiki.wikia.com/wiki/Thaddius_(original)

"They are both vulnerable to taunt."

**Comment by gemt** [comment]
Fixed
