### ISSUE TITLE
MSA scales with spellpower

### ISSUE THREAD

**Issue by AndreRieu1949** [elysium-project/naxxramas_ptr_feedback#115]
Item: 
http://db.vanillagaming.org/?item=23221
--
Equip: Chance to discharge electricity causing 100 to 151 Nature damage to your target.

Currently scales with spellpower, while according to comments [here ](https://web.archive.org/web/20060718003818/http://wow.allakhazam.com:80/db/item.html?witem=23221)it shouldn't

**Comment by gemt** [comment]
Fixed
