### ISSUE TITLE
Consecrated Sharpening Stone / Oil only lasting for 30 min. Should last for 60 min.

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/naxxramas_ptr_feedback#118]
https://wow.gamepedia.com/Consecrated_Sharpening_Stone

http://wowwiki.wikia.com/wiki/Quest:Consecrated_Sharpening_Stones

http://www.wowhead.com/item=23122/consecrated-sharpening-stone

https://web.archive.org/web/20070522002650/http://wow.allakhazam.com/db/item.html?witem=23122

Chinese post from 2006, translated to English reads:

Consecrated Sharpening Stone 
Requires Level 50 
Use: Increases the attack power by 100 points for 1 hour. 

http://bbs.nga.cn/read.php?tid=540579

**Comment by gemt** [comment]
DBCs has this error, it is impossible to know if it's the tooltip or the effect duration that's wrong without a vanilla video/screenshots. Will not prioritize figuring this out unfortunately.
