### ISSUE TITLE
Venom Stalker (15976) not working correctly

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#12]
http://db.vanillagaming.org/?npc=15976

The Venom Stalker currently only charges on pull. It puts out the poison correctly on that charge. However it doesnt do anything after the pull.

The Venom Stalker in the room just before Anub'Rekhan isnt linked to the pack. We managed to split-pull it.

source it should keep charging: https://youtu.be/cEsCSdp57d4?t=84
even better timestamp: https://youtu.be/cEsCSdp57d4?t=530

**Comment by Pleasant-Elysium** [comment]
Thanks for the report and for the sources.

**Comment by Braindot** [comment]
Necro Stalker (16453) is pretty much the same. Supposed to have the same ability, being the Poison Charge, which it currently only does on pull.

**Comment by kevmodrome** [comment]
Another source: http://z13.invisionfree.com/Tofu/ar/t1963.htm

**Comment by ettern** [comment]
Just a note:
A Venom Stalker/Necro Stalker will never use the poison charge ability if there are no people in charge range (10+ yards). I dont have any evidence for this, but it seems logical atleast. I've never experienced or seen a stalker charging a player that is close to the stalker (<10 yards).

Meaning if everyone where standing close to the stalker(s) that would explain the lack of charges. That said, if people where standing 10+ yards away from the stalker, and it does not do any charges after the inital pull, it is indeed a bug.

**Comment by gemt** [comment]
There are no limitations in the spell itself that indicates it should only target players a certain distance away, unlike a spell like warrior charge, which has a minimum range. That indicates to me it most likely should be able to target anyone, but of course, Blizzard could have done some handcoding. 

A fix for the repeatable behavior has been pushed. Not yet live.
