### ISSUE TITLE
Poisonous Skitterer (15977) model too big and slow movement

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#13]
http://db.vanillagaming.org/?npc=15977

These skitterers are too big and they move too slow.

Timestamp (8:09) in this video shows them significantly smaller then what they were on the PTR: https://youtu.be/cEsCSdp57d4?t=489

And at this point in the video (9:28) you can see the skitterers at a way faster pace then on the current PTR: https://youtu.be/cEsCSdp57d4?t=568

**Comment by Pleasant-Elysium** [comment]
Thanks for the report and for the sources.

**Comment by gemt** [comment]
Scale and speed has been adjusted. Not yet live and may need further adjustments.
