### ISSUE TITLE
Naxxramas Acolyte (15981) not working correctly

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#15]
http://db.vanillagaming.org/?npc=15981

The Naxxramas Acolyte is currently casting their Arcane Explosion and Shadowbolt Volley instantly. They should have a cast time of roughly 1-2 seconds as can be seen here (9:50): https://youtu.be/cEsCSdp57d4?t=590

**Comment by Pleasant-Elysium** [comment]
Thanks for the report and for the sources.

**Comment by ettern** [comment]
Can also add that they should be interruptable (Shield bash, pummel, counterspell etc.)

**Comment by Braindot** [comment]
They are apparently also doing like 3-4x the amount of damage with their Arcane Explosion. In the video at (10:00) you can see the AE doing roughly 550~ damage to the tank. Currently on the PTR it is doing 1900-2300 ish.
https://youtu.be/cEsCSdp57d4?t=597

Same for the Shadowbolt Volley. In the video at (9:46) the tanks gets hit by a triple volley, each hitting between 750-850. Currently on the PTR it was hitting for 1000-1200.
https://youtu.be/cEsCSdp57d4?t=586

**Comment by gemt** [comment]
The shadowbolt is not instant cast atm, its a 3 sec cast. The damage values are off for a currently unknown reason. Not finding any spells which makes more sense to use.

The arcane explosion spell has been changed to one which seems more correct.

Pushed, but not yet live.
