### ISSUE TITLE
Maexxna is Tauntable - should not be.

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#17]
Maexxna is tauntable but shouldn't be. Looking at old sources I haven't found any that explicitly say that she is not but no guide from those times mention anything about taunting. Having her tauntable makes the fight really easy since you can just sacrifice the tanks and battle res them. It makes the fight very easy.

As an aside I do not remember my retail guild taunting her. 

This might also apply to Anub and Faerlina

Sources: 
- https://web.archive.org/web/20080919093405/http://www.tentonhammer.com/node/26645
- http://wowwiki.wikia.com/wiki/Maexxna?oldid=197649

**Comment by gemt** [comment]
fix is pushed. Not yet live.
