### ISSUE TITLE
Anub'Rekhan Impale is majorly bugged

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#18]
The Impale from should originate from Anub and target a player. Players between and closeby should get hit and fly up. As it currently worked it seemed to be originating from a player and hitting every other one. In our raid everyone seemed to be hit even when spread out.

Sources:
"Impale: This is a nasty skill that randomly targets someone and throws them in the air, dealing about 3200 (Physical – mitigated with armor) damage to anyone in its area of effect (a straight stripe from Anub to the player). You can avoid having this wipe a raid by simply staying as spread out as possible." - https://web.archive.org/web/20090313075840/http://www.tentonhammer.com/node/26640

**Comment by ettern** [comment]
This is correct. The Impale ablity works like this:
[Visual](http://imgur.com/a/cxfTy)
Not sure if its 35 or 40 yard range.
This means that players standing more than 35-40 yards from Anub'rekhan, should never get hit by the impale.

**Comment by Braindot** [comment]
It is supposed to be a "line aoe" https://www.youtube.com/watch?v=zDzqh7nBkcc&feature=youtu.be&t=161 & https://youtu.be/zDzqh7nBkcc?t=215 (2nd example).

**Comment by Pleasant-Elysium** [comment]
Initial fix is implemented, will need feedback from other guilds after 1am server 7/13

**Comment by gemt** [comment]
This is assumed fixed now. If someone feel there are additional issues after the fix (applied sometime after 1am the 13th of July) feel free to open another issue.

**Comment by jmurraypplnet** [comment]
Anecdotal: Was not noticing fall damage after a spike hit.  Initial damage was applied but the fall back down did not seem to be adding on?  Also possible that it was all calculated at the time of the initial strike.

**Comment by gemt** [comment]
you do take some fall dmg, but not much. At least when I'm testing it. If anyone believe the knock-up should be higher, let me know.
