### ISSUE TITLE
Plagued Gargoyle (16446) not working correctly

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#19]
http://db.vanillagaming.org/?npc=16446

The Plagued Gargoyles are not using their Stoneskin ability at all. It is supposed to use this ability when they hit 20% health. It is supposed to do an /emote saying the following: "Plagued Gargoyle emits a strange noise." https://youtu.be/cEsCSdp57d4?t=1084 (18:04)

The ability itself is probably somewhere in the database, it just isnt implemented correctly?

**Comment by kevmodrome** [comment]
Looks like it's 30% according to this: http://z13.invisionfree.com/Tofu/index.php?showtopic=1963

"Stoneskin: At 30% the gargoyle will emit a strange sound and its hands will glow. You have 6 seconds to kill the gargoyle once at 30% or he will turn into stone and heal himself to full hp. This ability cannot be silenced, purged or interrupted."

**Comment by ettern** [comment]
30% is correct

**Comment by runklebc** [comment]
If you watch any of the vods I posted on my Issue you can see at one point one of them does heal to full on us. However it did not emote when doing so.

**Comment by ettern** [comment]
Here are some additional bugs regarding Plagued Gargoyle:
1. The Acid Volley debuff from two gargoyles should not be separated in two debuff slots, like [this](http://imgur.com/a/s2MhB). It should stack instead in one slot, like [this](http://imgur.com/KiF9fBq). 
Ref: [https://youtu.be/cEsCSdp57d4?t=17m31s](https://youtu.be/cEsCSdp57d4?t=17m31s)
2. Gargoyles should not be stunnable or CCed (kidney shot, hammer of justice etc..). The only reference for this would be to look into old videos and see if they could be stunned. I have yet too see a video of this.
3. Acid Volley debuff damage should be reduced drastically with a fair amount of of Nature Resistance (partial resists). We had a warrior yesterday with 240ish nature resistance, and he barely resisted (partial) any of the Acid Volley debuff damage.
Ref: [https://youtu.be/cEsCSdp57d4?t=17m34s](https://youtu.be/cEsCSdp57d4?t=17m34s) (check combat log)

What seemed to work:
1. Not possible to avoid acid volley by standing behind walls etc.
2. Range of acid volley seemed to be 60-70 yards.

**Comment by gemt** [comment]
fixed
