### ISSUE TITLE
Anub'Rekhan may spawn with 2 extra Crypt Guards

### ISSUE THREAD

**Issue by gemt** [elysium-project/naxxramas_ptr_feedback#2]
It's a known bug right now. Seems to happen on first pull. Ask a GM to clean them out for you until it's fixed if you cannot kill them yourself.

**Comment by Lorilay2** [comment]
http://wowwiki.wikia.com/wiki/Anub%27Rekhan_(original)

> There will be two adds that start the fight with Anub'Rekhan

**Comment by gemt** [comment]
2 extra crypt guards is what i meant

**Comment by Hozar1** [comment]
https://puu.sh/wHTjJ/fe4f21e15d.png better explained

**Comment by Selectah** [comment]
@gemt you mean Anub is already there with 4 guards in total? or after reset he doesnt despawn his additional guards?

Actually he starts as in wowwiki post from @Lorilay2 with two Guards and after 45seconds he summon again two guards.

Can you explain more? because i dont get your statement.

**Comment by ettern** [comment]
How it should work:
When engaging boss there should be two Crypt Guards. In addition, one Crypt Guard will spawn at Anub'Rekhan's initial engage point each time Anub'Rekhan is using the Locust Swarm ability.

**Comment by gemt** [comment]
this was fixed before most guilds got to him. Sorry for not updating this.
