### ISSUE TITLE
Spirit of Naxxramas (16449) not working correctly

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#20]
http://db.vanillagaming.org/?npc=16449

The Spirit of Naxxramas in the outer ring before Maexnna wasnt using any abilities. It is supposed to be invisible in the first place (only visible with invis detection buff from warlocks).

Second, its supposed to summon/spawn a "Ghost of Naxxramas" http://db.vanillagaming.org/?npc=16419 from a red portal similar to the portals that Blackwing Lair Warlocks spawn https://youtu.be/cEsCSdp57d4?t=987 (16:27). It is also supposed to spawn one of these ghosts on death.

And last but not least, its supposed to do a AoE shadowbolt volley. Hard to see but if you pause the video at 16:24-16:25 you can see it go out. Seemed to hit for 1700~ on the tank. https://youtu.be/cEsCSdp57d4?t=985

**Comment by Braindot** [comment]
Actually not 100% sure if they are supposed to be visible. The video shows the warrior not having any invis detection buff on him, so it might only be the Shade of Naxxramas in the DK wing that is supposed to be invisible.

**Comment by gemt** [comment]
Shadowbolt volley and portals+ghosts implemented and pushed. Not yet live.
Waiting with the invisibility part until we some more info on it.

**Comment by runklebc** [comment]
Spirit of Naxxramas are only invisible in 3.0.

In 1.11 they should be visible with no buffs.

But I agree with this Issue, it was not using any abilities.
