### ISSUE TITLE
----- See #4, Close this one out

### ISSUE THREAD

**Issue by sneakdella** [elysium-project/naxxramas_ptr_feedback#21]
Title says all. It is supposed to tick for poison damage. Some proof I guess there was a guide written a long time ago.

http://leftoversraiding.org/index.php/topic/855/1

**Comment by ettern** [comment]
"It is also just as important that the tank avoid stepping into the slime ring, as it will put a debuff reducing all stats to 10% of normal, effectively dropping his max health by 5-6000 points."
[http://wowwiki.wikia.com/wiki/Anub%27Rekhan_(original)](http://wowwiki.wikia.com/wiki/Anub%27Rekhan_(original))

**Comment by Pleasant-Elysium** [comment]
#4
