### ISSUE TITLE
Wrong pack composition in the first room right after Green Area in Spider Wing

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#23]
The packs with 4 Dread Creepers and a Tomb Horror currently have a Crypt Reaver instead of the Tomb Horror. Talking about this pack: https://i.imgur.com/ysObB4V.png

Tomb Horror: http://db.vanillagaming.org/?npc=15979

source: https://youtu.be/cEsCSdp57d4?t=928 (15:29 ish)

**Comment by gemt** [comment]
Should be fixed
