### ISSUE TITLE
Naxxramas Acolyte and Naxxramas Cultist are supposed to /kneel

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#24]
Like the title says... As can be seen in this video, starting from 9:28 https://youtu.be/cEsCSdp57d4?t=568 both are supposed to kneel, all looking at the boss. Currently on the PTR they are all standing upright.

Naxxramas Cultist: http://db.vanillagaming.org/?npc=15980
Naxxramas Acolyte: http://db.vanillagaming.org/?npc=15981

**Comment by gemt** [comment]
Kneeling on spawn is pushed. Not yet live.

Currently unknown to me if they should go back to kneeling if someone wipe and they reset.
