### ISSUE TITLE
Corpse Scarabs Spawning Out of Nowhere / Inconsistent 

### ISSUE THREAD

**Issue by sneakdella** [elysium-project/naxxramas_ptr_feedback#26]
Corpse Scarabs were spawning behind the group and not from the boss and not from the Crypt Guards when they were all still alive.

From http://wowwiki.wikia.com/wiki/Anub%27Rekhan_(original)

Other
10-15 seconds after they are killed, Anub'Rekhan can use an attack to explode either Crypt Guard corpse, causing ~10 Corpse Scarabs to spawn.
Distance to Anub'Rekhan seems to be a factor to whether or not he will explode the corpse.
Killing the Crypt Guards at the same spot will make it easier for the raid to control the Corpse Scarabs when they spawn. (Be careful about tanking them on top of the dead Guards, otherwise mages can't stand in close to Frost Nova with out being cleaved)

Corpse Scarabs
6,000 health, hit for 400 physical damage.
If coming from a Crypt Guard, ~10 will spawn. A player death will cause 5 to spawn.
Susceptible to all forms of crowd control, Frost Nova is most effective at controlling them.
Note: Aggro seems to work differently than normal mobs. Once the add is on a target, dps alone will most likely kill it before aggro is transferred to the DPSer. This can lead to a wipe if several loose bugs aggro the hunter or tank shortly before locust swarm.

**Comment by gemt** [comment]
Not seen this happen anywhere yet. Can you provide a screenshot/video of it happening? Keep in mind they do spawn from player corpses as well.

**Comment by Ztrijji** [comment]
The Crypt Guards "explode" at random intervals, not a set 10-15 second after death.

[https://www.youtube.com/watch?v=m4vsRk1tf9k](url)

First Crypt Guard dies at 0:44 and scarabs spawns from corpse at 1:10. 26 seconds from kill to scarab spawn.
Second Crypt Guard dies at 1:17 and spawns scarabs from corpse at 2:27. 70 seconds from kill to scarab spawn.
Third Crypt Guard dies at 2:07 and spawns scarabs from corpse at 3:14. 67 seconds from kill to scarab spawn.
Fourth Crypt Guard dies at 3:33 and spawn scarabs from corpse at 4:08. 35 seconds from kill to scarab spawn.

**Comment by jmurraypplnet** [comment]
The scarabs were hitting for 1k+ damage rather than the expected value.

**Comment by sneakdella** [comment]
They were coming from the entry door, like just out of the blue. No players dead.

Could it be that the corpses are exploding but the Corpse Scarabs are spawning elsewhere?

**Comment by gemt** [comment]
Changes were made do their spawnlogic after previous test. Will see how it works next ptr session before closing
