### ISSUE TITLE
Maexxna - Spider spawns attacking too slow

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#28]
Spider spawns should hit very fast, approximately 1 hit each 0,5 seconds. Should hit for about 150 on a leather class. [https://youtu.be/ECEJNlkZlt0?t=5m](https://youtu.be/ECEJNlkZlt0?t=5m)

Apparently they have a 2 seconds attackspeed on ptr: [https://www.twitch.tv/videos/158645236](https://www.twitch.tv/videos/158645236) (00:48:30)

**Comment by gemt** [comment]
Fix is pushed. Not yet live
