### ISSUE TITLE
Comprehensive Spider Wing Writeup

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#29]
**Anub'Rekhan** 
Spikes were fixed by the time we got there. 

**Grand Widow Faerlina**
Everything good.

**Maexxna:**
Should be immune to taunt
Hit Box way too small - Evidence from Vanilla video, youtube time stamped: You can see melee swinging from just right around the edge of the legs. https://youtu.be/ec9rf8woNAI?t=120
Aggro range way too small - Should be able to enter the left side of the room and hug the wall within 5-10 yards. Once slightly further inside than that she should aggro.

**Trash:**
Venom stalkers - Shouldn't charge immediately. Should charge random ranged after a few seconds.
Plagued Ghost - Rupture hitting for 800. Looks correct.
Necro Stalkers - Should charge ranged. Shouldn't charged to start the pull, but should charge ranged after being pulled a 5-10 seconds later
Plagued Gargoyle -  Should emote when healing back to full
Slime - Doesn't work, should deal damage to you.
Poisonous Skitter - Needs increased movement speed
Venom Stalker - Venom Spit should have timer and max range
Venom Stalker - should have increased damage maybe?

**Videos of run:**

https://www.twitch.tv/forest_eye/videos/all
Twitch
Forest_eye - Twitch

https://www.twitch.tv/chakaog/videos/all
Twitch
ChakaOG - Twitch

https://www.youtube.com/watch?v=i-5G8xGVu3U

**Comment by superbistro** [comment]
https://www.twitch.tv/videos/158821306

**Comment by runklebc** [comment]
Patch notes since Naxxramas Test release:

GENERAL

Fixed issue with Naxxramas Slime debuff not applying properly
Releasing spirit inside Naxxramas now releases you to the nearest graveyard
TRASH

Added immunities to various Crowd Control abilities.
Increased damage dealt and attack speed of various creatures
Improved Venom Stalker charge AI
Increased Poisonous Skitterers speed and lowered its scale
Fixed AI for Spirit of Naxxramas
Fixed Naxxramas Acolytes’ spells
Added Kneel animation for Naxxramas Acolytes and Cultists
Fixed “Web-pull” effect.
Plagued Gargoyle Acid Volley now stacks in one debuff.
Plagued Ghouls should now also cleave
ANUB’REHKAN

Fixed issue causing additional Crypt Guard adds spawning at zone-in
Fixed issue causing Crypt Guards to not properly despawn or spawn
Fixed bug with Impale ability
Reduced Corpse Scarab damage
Fixed AI for Corpse Explosion ability
Fixed bug causing Corpse scarabs to not despawn
FAERLINA

Appropriate Crowd Control immunities added to Worshippers and Followers
Fixed Poison Bolt AI
Fixed an issue with Enrage
MAEXXNA

Maexxna’s Hitbox increased drastically
Spiderlings damage and attack speed increased
Added missing taunt immunity
