### ISSUE TITLE
Grand Widow Faerlina - Adds not working correctly, spells might not work correctly either?

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#30]
The adds on Faerlina were sheepable but shouldn't be. Tactics from old sites say that the adds should be killed quickly or off-tanked. The followers should be stunnable, the worshippers should not.

We seemed to have someone being able to interrupt the Rain of Fire, pretty sure that's not working correctly. Not 100% sure about this.

In addition to this, the silence from the worshippers should only silence her nature school spells, the RoF should continue casting. Note that the silence should only hinder the Poison Volley for 30 seconds, even if you use it when she is enraged.

The followers should have an AoE silence ability according to TenTonHammer: "The Followers must be off tanked away from the raid as they have a very annoying AoE silence. They also can randomly charge people, so be sure they are under control!"

Sources:
http://wowwiki.wikia.com/wiki/Grand_Widow_Faerlina_(original)

"Anytime you sacrifice a Naxxramas Worshipper you will gain a 30 second immunity from this skill [Poison Volley]."
"Sacrificing Worshippers also stops her Poison Bolt Volley for about thirty seconds."
https://web.archive.org/web/20080919093400/http://www.tentonhammer.com/node/26643

**Comment by gemt** [comment]
The rain of fire is not interruptable. It's an instant cast. Certain addons may show it as a channel, but that's just an addon bug.

The 30 sec poison silence after sacrificing a follower should already be working. Report back if you are adamant it's not. The RoF is not silenced

Followers should already have their AOE silence.
