### ISSUE TITLE
Herbs spawn times have decreased significantly on Elysium and nobody cares

### ISSUE THREAD

**Issue by BlackGronk** [elysium-project/naxxramas_ptr_feedback#31]
Nuff said.

**Comment by kevmodrome** [comment]
Wrong repository

**Comment by BlackGronk** [comment]
Yeah I know, they just wouldn't acknowledge that there was a problem so I decided to badger effectively.

**Comment by Xerxey** [comment]
Please delete any irrelevant issues in this repository. It is unnecessary to flood this repository and negatively impacting the PTR testing of upcoming content.
