### ISSUE TITLE
Carrion Spinner (15975) not working correctly

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#34]
The ability "Spider Web" ([http://db.vanillagaming.org/?spell=28434](http://db.vanillagaming.org/?spell=28434)) is not working correctly.

Correct behaviour: It should pull a random player up to the Carrion Spinner's melee range.
Ref: [https://youtu.be/cEsCSdp57d4?t=2m10s](https://youtu.be/cEsCSdp57d4?t=2m10s)
Current: You get "web-knocked" up in the air.
Ref: [https://www.youtube.com/watch?v=i-5G8xGVu3U](https://www.youtube.com/watch?v=i-5G8xGVu3U) (28:38)

**Comment by gemt** [comment]
Fixed
