### ISSUE TITLE
Naxx Trash Farming (Plague Wing) - Ghouls and Plague Slimes should be able to be slowed/snared/stunned

### ISSUE THREAD

**Issue by theloras** [elysium-project/naxxramas_ptr_feedback#35]
In order to allow for solo or small group farming of Naxx Trash epics:

**Naxxramas trashmobs**
_Published on Dec 29, 2006_
https://www.youtube.com/watch?v=0l06mPcJ4r4

**Naxx Trash**
_Published on Jul 26, 2006_
https://www.youtube.com/watch?v=AH9g13Hmbbc

**Farming Naxx Trash**
_Published on Oct 13, 2006_
https://www.youtube.com/watch?v=Dc013bgczcU

**Naxxramas Trash Farming**
_Published on Oct 26, 2006_
https://www.youtube.com/watch?v=-FB-knw7MI8

**Naxx trash 7man**
_Published on Aug 16, 2006_
https://www.youtube.com/watch?v=CrKs6RBfyfg

The Ghouls should be able to be Turned (Paladin Undead Fear) or Shackled as well iirc.

**Comment by theloras** [comment]
Also this video showing a Death Knight wing mob being solo kited:

**mage solo naxx**
_Published on Jul 29, 2006_
https://www.youtube.com/watch?v=9OxFm4Jqr2k

Although I am puzzled as to why the rest of the mobs deagroed him in the centre area.

**Comment by runklebc** [comment]
I don't think the stunning is correct. It appears to me that mobs should only be susceptible to Roots/Slows/Tongues/Turn Evil.

All Wings:
https://www.youtube.com/user/tlwguild/videos?sort=da&view=0&flow=grid
https://www.youtube.com/channel/UCaUQZVtMtE7tzmcUu5_d4Ig

https://www.youtube.com/watch?v=Dc013bgczcU (Ghouls got frost bolt/CoC'd)
https://www.youtube.com/watch?v=9OxFm4Jqr2k (Frost Bite Proc/Nova)

Spider Wing:
https://www.youtube.com/watch?v=cEsCSdp57d4
https://www.youtube.com/watch?v=ofbTdgP1pbA
https://www.youtube.com/watch?v=7zyyzmDn9j0 (2:44, pulled Human pack, didn't see anything on pull?)

Death Knight:
https://www.youtube.com/watch?v=y3PUGYve2E4
https://www.youtube.com/watch?v=aGvJFtDsWsw - Blackout procs on one of the mobs showing stunnable, but is boss ad. Also earth bind.

**Comment by theloras** [comment]
found a stun
https://www.youtube.com/watch?v=-FB-knw7MI8&feature=youtu.be&t=300
looks like a hunter pet intimidation on the ghoul

https://youtu.be/-FB-knw7MI8?t=423
blob is stunned from hunter pet again and again at 450 from the other hunter's pet

**Comment by theloras** [comment]
here's a Ghoul being shackled:

https://youtu.be/CrKs6RBfyfg?t=75

**Comment by theloras** [comment]
double ghoul shackle plus actual text in the video giving instructions to do it lol:

**Naxx Raid**
_Published on Nov 12, 2006_
https://youtu.be/eR5wh1VMZ7o?t=33

**Comment by theloras** [comment]
Rogue landing a Cheap Shot stun on a Ghoul:

**Sacri Templarus @ Grim Batol killing trashmobs with 12 ppl - Vertez POV**
_Published on Oct 31, 2006_
https://youtu.be/WpnmUOpT9k0?t=80

**Comment by gemt** [comment]
Thanks for all of these reports. These mobs should be correct on next PTR session
