### ISSUE TITLE
Poison Slime doesn't deal damage nor reduce max HP by 90%

### ISSUE THREAD

**Issue by Pleasant-Elysium** [elysium-project/naxxramas_ptr_feedback#4]
The green poison slime throughout the instance does not deal damage nor reduce max hp by 50%.

**Comment by blubba22** [comment]
Seconded. Same for us.

**Comment by BBCnewstoday** [comment]
It should apply http://db.vanillagaming.org/?spell=28801 to anyone who enter slime. 
I looked into this issue like 2months ago, but looks like there's major issue in LiquidType.dbc reading. 
I'm currently working on adding temp solution, based on areatriggers, not good solution, but still...

**Comment by StadenElysium** [comment]
Fixed in the main repo.

**Comment by gemt** [comment]
Fixed in naxx repo.
