### ISSUE TITLE
Noticed bugs

### ISSUE THREAD

**Issue by Fweezd** [elysium-project/naxxramas_ptr_feedback#40]
Hello,

I haven't been through all issues reported so I apologize for those that will be repeated here. Voila the guild BnH's list:

Naxx bugs : entrance doesn’t always work when dead. Must Jump around for a while in order to enter.

First boss :
-	Scarab are really bugged, they don’t seem to spawn from corpses, but sometimes randomly spawns in the room. Scarabs spawn in 2 waves? (It seemed)
-	Scarabs on evade mode
-	Anub’Rekan ability doesn’t always knock up in the air
-	Anub’Rekan is pitch black and doesn’t have any designs (can upload a screen if necessary)
-	His scale is quite small, he should be bigger
-	The respawn of Scarab Corpse when the guard dies is irregular
-	Scarab Corpse damages are way too high, and don’t enter combat directly (hence Evade mode)
-	Random crashes when boss cast skills, the whole Raid got DC several times

Faerlina : 
-	Worshippers can be sheeped, shouldn’t be possible
-	Enrage mode damages are too low.

Trashes : 
-	One Necro Stalker Patrol after Anub’Rekan is stacked up and patrols weirdly 
-	Necro Stalker damages are too low, perhaps all spider damages are too low
-	All trash mobs can be CCed
-	Control Minded Naxxramass Cultist port directly at the priest when Control Mind breaks

**Comment by blubba22** [comment]
"Anub’Rekan is pitch black and doesn’t have any designs (can upload a screen if necessary)"

Do you have Smooth Shading deactivated? Because if you don't some models appear to be completely black (like Thunderfury).

**Comment by gemt** [comment]
Most issues here have been solved. Some have no sources and should be backed up or given. If you find any remaining issues, please open a new issue (preferably separate each bug in its own github-issue).
