### ISSUE TITLE
Paladin / Shaman item

### ISSUE THREAD

**Issue by Crematorya** [elysium-project/naxxramas_ptr_feedback#42]
These things must fall only to the alliance:
Belt of the Grand Crusader - http://db.vanillagaming.org/?item=23666
Spaulders of the Grand Crusader - http://db.vanillagaming.org/?item=23667

These things must fall only to the horde:
Leggings of Elemental Fury - http://db.vanillagaming.org/?item=23665

**Comment by gemt** [comment]
Fixed
