### ISSUE TITLE
spider zone bugs

### ISSUE THREAD

**Issue by ironmilk** [elysium-project/naxxramas_ptr_feedback#44]
1. Venom stalker can't cast poison bolts. It should cast poison bolts.
2. Mob can be separated from their crowd.It shouldn't be.
3. Green water don't cause damage. It should do.
4. When crypt guard died, it didn't spawn corpse scarabs. And if you wiped, these corpse scarabs didn't disappear in chance. It lasts 3-5 minutes.
5. posionous skitterer shouldn't be slowed.
6. All boss and trash in spider zone has a lower damage than expectation, especially in enrage.

**Comment by gemt** [comment]
Venom Stalkers does poison charge at random intervals which leaves a poison dot. If they should do a poison bolt as well of some sorts, can you provide some source?

**Comment by gemt** [comment]
Everything here should be fixed at this point
