### ISSUE TITLE
List of some issues: 

### ISSUE THREAD

**Issue by blubba22** [elysium-project/naxxramas_ptr_feedback#45]
- These Acolytes adds weren't linked: http://i.imgur.com/mGBrfRr.jpg

- Tomb Horrors only had like 9,3k HP: http://i.imgur.com/vhBIO94.jpg

- These spiders didn't reset to their places after we wiped: http://i.imgur.com/WNqwSTD.jpg

- Pack before Nerub isn't linked properly (already reported this earlier): http://imgur.com/a/XHaj0

- I don't how it's supposed to work but the Scarabs didn't despawn after a wipe and we had to kill them all afterwards and there were so many of them that FPS tanked. Might want to have them despawn after wipe.

**Comment by gemt** [comment]
Acolytes are linked.
Tomb horrors hp changed.
Spiders _should_ reset 
The corpse scarabs are _changed_
