### ISSUE TITLE
Grand Widow Faerlina - Movement speed

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#46]
Grand Widow Faerlina movement speed is too low on PTR.
I watched some footage from PTR yesterday and noticed how you could kite her around so she barely could get in any hits. 
Lets take a look at the inital pull and compare:
Retail: [https://youtu.be/83TB9FA64e4?t=30s](https://youtu.be/83TB9FA64e4?t=30s) (skull)
PTR: [https://www.twitch.tv/videos/159657028?t=00h58m00s](https://www.twitch.tv/videos/159657028?t=00h58m00s) (sqaure)

Then when she is running around because MT is dead:
PTR: [https://www.twitch.tv/videos/159657028?t=00h59m09s](https://www.twitch.tv/videos/159657028?t=00h59m09s)
Retail: [https://youtu.be/83TB9FA64e4?t=1m45s](https://youtu.be/83TB9FA64e4?t=1m45s)

I have no clue what the movement value should be, but I guess the devs can find out by comparing the clips.

**Comment by gemt** [comment]
increased it a bit, should be more in line with what we see on the retail videos.
