### ISSUE TITLE
Abominations should not be slowed

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#52]
From current PTR:
Patchwork Golem getting slowed: [https://youtu.be/U00VsAdxOQA](https://youtu.be/U00VsAdxOQA)
Bile Retcher getting slowed: [https://youtu.be/piLXcj9ClfM](https://youtu.be/piLXcj9ClfM)

I dont have any proper evidence that they should not be slowed other than this: https://www.youtube.com/watch?v=VrykhhdPfc4

Another evidence would be that there are no videos of solo farming the abominations, simply because they could not be slowed.

**Comment by gemt** [comment]
fixed
