### ISSUE TITLE
Frozen Rune locations

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#54]
**General info**
- Can only be looted if you have a [Word of Thawing](http://db.vanillagaming.org/?item=23055) in your bag. Once the rune is looted, one Word of Thawing will be consumed.
- Frozen Rune objects do not respawn in a raid ID.
- They are often seen in boss chambers, but most likely only one in each chamber. (Sometimes there are none)
- Each Frozen Rune object will yield between 3 and 6 Frozen Runes.

Based on old videos, these are the locations I've found so far (mostly spider wing):
[http://imgur.com/a/RfkvI](http://imgur.com/a/RfkvI)

**Update 1(locations from Plague Wing):**
http://imgur.com/a/NpS9A

**Update 2(locations from Abomination Wing):**
http://imgur.com/a/yVi2z
Video for last image shows that it should be possible to loot 6 frozen runes from one object.

If you find other locations, please add it here.

**Comment by runklebc** [comment]
This is fantastic work Ettern. I don't have anything to add. Just wanted to say good fucking job.

**Comment by ettern** [comment]
Update1: Added locations from Plague Wing.

**Comment by ettern** [comment]
Update2: Added locations from Abomination Wing

**Comment by gemt** [comment]
To anyone willing to help with this search effort, unfortunately we dont have a better way to find their location atm than how Ettern is doing it, which is simply searching through an endless amount of vanilla naxx videos for their location. If anyone wish to help find more locations, just start watching videos and look for them in the walls.

**Comment by Skarseth** [comment]
> They are often seen in boss chambers, but most likely only one in each chamber. (Sometimes there are none)

Regarding this part, do you know for a fact there are instances where there are non at all in the boss rooms, or do you mean you have seen fight recordings where you see none, in which case it might just be because players have already looted them.

**Comment by ettern** [comment]
"Each object will yield beetween three and six runes."
https://wow.gamepedia.com/index.php?title=Frozen_Rune&oldid=279709

**Comment by Zoldam** [comment]
I recorded all rune locations (100% boss room accuracy, iffy % Outer Ring accuracy) when I worked on Naxx for another server a few years ago.
