### ISSUE TITLE
Sewage Slime missing the nature damage aura

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#57]
This aura should hit everyone in a 5-10yards range with 700ish nature damage every 3 seconds (resistable).

https://youtu.be/VrykhhdPfc4?t=3m49s

**Comment by gemt** [comment]
It has been added and will be live next PTR session. the 700 dmg from the linked video is most likely the 1.11 PTR value, and must have been changed at some point before 1.12, because there are no relevant spells dealing around 700 nature damage. 

As #68 mentions, its around 250 dmg instead.
