### ISSUE TITLE
Paladin T3 6 Set Bonus Not Working

### ISSUE THREAD

**Issue by ScuPal004** [elysium-project/naxxramas_ptr_feedback#58]
Pally t3 6/9 set bonus isn't proc'ing.

**Comment by cnjzxy** [comment]
Have the same problem with him, bug confirmed.

**Comment by booblebath** [comment]
Bug confirmed just today

**Comment by booblebath** [comment]
Also the 3 set bonus doesnt work either. should be healing for 81 but heals for the same 61.
