### ISSUE TITLE
Patchwork Golem missing abilities

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#59]
- 360° cleave every 10-20 seconds. There will be an animation first (like casting a heal). This cleave do approx 1300 damage to a tank. 3750 on cloth.
> 360° Cleave (~3750 damage on cloth) (The Cleave is chain-targeting like C'Thun Eyebeam and looks like a heal being cast when it's being prepared.)

- War Stomp stunning players in a 5-10 yards range for 4 seconds and do 1200ish damage. On PTR it  seems that they do knockback instead.

[http://z13.invisionfree.com/Tofu/index.php?showtopic=1963](http://z13.invisionfree.com/Tofu/index.php?showtopic=1963)
[https://youtu.be/VrykhhdPfc4?t=2m58s](https://youtu.be/VrykhhdPfc4?t=2m58s)

**Comment by gemt** [comment]
Fixed. May not hit the PTR until tomorrow or the day after.
