### ISSUE TITLE
Spiders can boot you up to the top of the entrance hall - can't reach your corpse to rez

### ISSUE THREAD

**Issue by vehystrix** [elysium-project/naxxramas_ptr_feedback#6]
I got booted to the top of the entrance hall (little ledge that goes around) Wher a spider followed me up to and killed me.
My corpse is no longer in range to rez once dropped down, nor is it LoS from a healer trying to rez
![capture](https://user-images.githubusercontent.com/7142781/28134542-91c87dda-6743-11e7-973f-94a63c897d20.PNG)

**Comment by Pleasant-Elysium** [comment]
Fixed due to releasing spirit to graveyard.

**Comment by ettern** [comment]
What kind of spider did that? It seems to be some of the trash packs, if so, then this is a bug, cause none of the spider packs should "boot" you up to the top.
The only spider that could possible cause this is the Carrion Spinner, but that spider should pull you, not knock you up.

This might be a bug!

**Comment by gemt** [comment]
This should be fixed now. The pull effect has been improved.
