### ISSUE TITLE
Sludge Belcher missing in Abomination Wing

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#60]
NPC link: [http://wowwiki.wikia.com/wiki/Sludge_Belcher](http://wowwiki.wikia.com/wiki/Sludge_Belcher)
More info: [http://z13.invisionfree.com/Tofu/index.php?showtopic=1963](http://z13.invisionfree.com/Tofu/index.php?showtopic=1963)
They seem to be patrolling between Patchwerk and the room where Grobbulus throws  3 slimes.

[https://youtu.be/agWfYn0piY8?t=6m55s](https://youtu.be/agWfYn0piY8?t=6m55s)
[https://youtu.be/IbRODBLeqk4?t=2m20s](https://youtu.be/IbRODBLeqk4?t=2m20s)

From current PTR:
Im fairly sure Patchwork Golems should not patrol at all.
http://imgur.com/a/KXqad

**Comment by JosipbrozElysium** [comment]
Correct, they were temporarily removed as they would spawn infinitely and would thus lag/crash the server. Working on a fix!

Best regards!
