### ISSUE TITLE
Noth->Heigan gauntlet Respawn timer

### ISSUE THREAD

**Issue by gemt** [elysium-project/naxxramas_ptr_feedback#61]
Need information on what the respawn timer should be in the gauntlet. Currently 2 minutes, but got no good sources on this topic.

**Comment by ettern** [comment]
**Tunnel before Heigan the Unclean**

Plague Beast

- Tank away from raid
- Disease aura, doing damage to raid
- Stomp 2000 damage
- **1 per wave, more than 4 minutes respawn**

Grub

- Slime Burst - Inflicts 232 to 268 Nature damage to nearby enemies, and reduces their movement speed by 50% for 5 sec.
- Comparatively low damage.
- **2 per wave, 30 seconds respawn.**

Bat

- Charges random players.
- Putrid Bite - Increases the damage taken by an enemy by 120 for 30 sec.
- **5 per wave, 30 seconds respawn**

https://wow.gamepedia.com/Heigan_the_Unclean_(original)

**Comment by gemt** [comment]
Respawn timers are adjusted to the values by Ettern for now.
