### ISSUE TITLE
Gluth - Mortal Wound bugged

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#63]
We had an instance where Mortal Wound disappeared after 5 stacks on our tank. Have no video of the event but we had no problem sticking to one tank.

The debuff should stack and has a 15 second length.

"Mortal Wound - Stackable debuff on the MT that reduces healing by 10%. (Identical to the one used by Kurinnaxx and Fankriss, except he isn't tauntable.)" according to Wiki

**Comment by gemt** [comment]
Possible the tank just had a crazy luckstreak of avoidance? Not seen this happen before.

**Comment by kevmodrome** [comment]
It is for sure possible. I will try to to find a combat log of fight, I forgot to turn it on myself unfortunately.

**Comment by kevmodrome** [comment]
Checked a recording and it seems the main tank was feared and most likely dodged the application of a new Mortal Wound. Closing because it's probably working correctly.
