### ISSUE TITLE
Wrong pack composition DK Wing first packs

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#64]
Title says it all. First two packs in the Death Knight Wing have the wrong mobs in them. 

Talking about this pack: https://i.imgur.com/UM0KXiN.png

Currently on the PTR we have a Deathknight and two Risen Squires. The Risen Squires should be Risen Deathknights as can be seen in this video https://youtu.be/K-dYEy7OgAY?t=72 and this video https://youtu.be/agWfYn0piY8?t=57.

**Comment by Braindot** [comment]
Actually not just the first two packs, but pretty much anywhere. Risen Squires should be Risen Deathknights.

**Comment by gemt** [comment]
Same as the other name issue bugs, it's already correct, but need to delete WDB to see the correct name.
