### ISSUE TITLE
Gluth - Zombies not applying debuff often enough?

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#65]
Not sure how this is scripted but for us it seemed like the zombies didn't apply the Infected Wound debuff often enough. We could almost tank them instead of tanking them.

Evidence from old videos show all of the guilds kiting the zombies. Here for example: https://www.youtube.com/watch?v=fEuxVfBckuA

**Comment by smkrus** [comment]
It appears that multiple attacking the same person will overwrite the debuff rather than stack it.

**Comment by gemt** [comment]
They overwrite eachother indeed. Its been fixed and will be live on next PTR session
