### ISSUE TITLE
Abomination Wing - Sewage Slimes missing AoE ability

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#68]
The Sewage Slimes are supposed to have an AoE ability doing 250 damage/3 seconds.

"Weak AoE nature damage aura - ~250 damage/3 seconds"- http://wowwiki.wikia.com/wiki/Sewage_Slime?oldid=240664

**Comment by gemt** [comment]
It has been added and will be live next PTR session
