### ISSUE TITLE
Abomination Wing - Embalming Slimes missing AoE ability.

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#69]
You should basically die very quickly if you go close to these slimes. This didn't seem to be the case.

According to source: "Emit a Slime Cloud doing 2000 - 3000 Nature damage to anyone withing a 10 yard radius."

Source: http://wowwiki.wikia.com/wiki/Embalming_Slime?oldid=240666

**Comment by gemt** [comment]
They do use the ability, but the frequency is currently set to every 5 seconds, so its possible to run inn and out and DPS them as melee. I dont know the correct frequency, but I have increased it and that will be live on next PTR session.

**Comment by kevmodrome** [comment]
Ah! That exaplins why so few people died then. It's hard to gauge the frequency for sure. I will try to see if I can find a video that shows people taking damage.

**Comment by kevmodrome** [comment]
Here is a video of it. It's unfortunately sped up so not sure about the frequency anyway. It looks to be around 10x speed up? Slowing it down to 0.25x speed and just looking at it it seems to be ticking every 2 seconds, so 5 seconds might be close to correct.
