### ISSUE TITLE
Invisible packs in DK wing

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#70]
During our raid we encountered several "invisible" packs. They would become visible within aggro range upon pulling aggro. A few packs on the platform above Razuvious. The Shade of Naxxramas + 2x Necro Knights pack after the room with the Unholy Weapons in them. Both Necro Knights were invisible to us, only appearing upon pulling the Shade.

Not quite sure what caused this bug to happen, but it happened for everyone in the raid.

edit: Greater Invis detection didnt help :D

**Comment by gemt** [comment]
Not seen this myself before. If any other guilds have had the same problem, please report inn.

**Comment by kevmodrome** [comment]
I don't believe we encountered this.

**Comment by Braindot** [comment]
Here's a few clips from our raid last night in which you can see the packs being invisible to us.
Naxx PTR DK Wing Invisible packs before Razuvious: https://www.youtube.com/watch?v=aqH6gX3SC_I
Naxx PTR DK Wing Invisible packs before Razuvious v2: https://www.youtube.com/watch?v=xM_lRFajIs0
Naxx PTR DK Wing Invisible packs after Unholy Weps room: https://www.youtube.com/watch?v=OXsfnEvhiCU

**Comment by gemt** [comment]
Got absolutely no idea what caused this. Won't be any changes for the next ptr session, we will see if it happens again. Could be some freak random bug
