### ISSUE TITLE
Grobbulus Mutating injection and its clouds acting weird

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#71]
Here's a clip from our raid last night: https://www.youtube.com/watch?v=0660S23Xw_8

The clouds seem to be dissappearing rather fast or not even appearing at all. Might have to do with the distance to the boss, being cleansed while jumping, I dont know to be honest.

All in all just seems off compared to retail videos like:
https://www.youtube.com/watch?v=UW-MGGfUGf8
https://www.youtube.com/watch?v=egvkHLUUHkU
https://www.youtube.com/watch?v=gNRgMUMU4Zc

**Comment by runklebc** [comment]
Scuba Cops PTR Test, additional evidence.

**Grobbulus:**

**Issue:** Poison Dispel not dropping cloud

https://youtu.be/Gur4D9iAKrs?t=11563 (PTR - You can see no gas pools are being spawned where the players are running to.)
https://youtu.be/egvkHLUUHkU?t=79 (Retail)

**Comment by gemt** [comment]
The cloud from the mutagen injection was bugged. It's been fixed and will be live next ptr session
