### ISSUE TITLE
Gluth: Zombie Chow move too quickly during decimate

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#72]
# Scuba Cops PTR Test Feedback

### Issue - Zombie Chow move too quickly during decimate

**Evidence PTR vs Retail:**

https://youtu.be/Gur4D9iAKrs?t=12103 (PTR)

https://youtu.be/mTxfRCfs_Bo?t=60 (Retail)
https://youtu.be/T6MhxKjApMg?t=182 (Retail)

**Comment by gemt** [comment]
The mobs in the retail videos you linked are slowed, none of the mobs on the ptr video are slowed. With CoC the mobs move at the same speed as in the retail videos. The mobs have no special runspeed mods, and the decimate spells have no runspeed effects.
