### ISSUE TITLE
Gluth: Door to Thaddius should be closed until Gluth is killed

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#73]
# Scuba Cops PTR Test Feedback

### Issue - Door to Thaddius should be closed until Gluth is killed

**Evidence PTR vs Retail:**

https://youtu.be/Gur4D9iAKrs?t=12103 (PTR)

https://youtu.be/T6MhxKjApMg?t=102 (Retail)

**Comment by Braindot** [comment]
Not 100% sure but I think I remember one of the GM's saying they've removed all the doors for PTR.

**Comment by gemt** [comment]
Most doors were removed for the PTR yes, since they wouldnt open if the 30min automatic despawn triggered.

**Comment by runklebc** [comment]
Good to know!
