### ISSUE TITLE
Gothik the Harvester: Should teleport aligned to the middle of both sides of the room in phase 2

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/naxxramas_ptr_feedback#74]
# Scuba Cops PTR Test Feedback

### Issue - Gothik the Harvester should teleport aligned to the middle of both sides of the room in phase 2. Should be aligned with the central spawn points.

**Evidence PTR vs Retail:**

https://youtu.be/Gur4D9iAKrs?t=3544 (PTR)
https://youtu.be/VIatOCAItjQ?t=282 (Retail)

**Comment by R4k3te** [comment]
He should also reset threat on teleport and shoot his shadowbolts at random target in quick succession instead of on the highest target in his threatlist.

**Comment by Forest-runklebc** [comment]
Gothik still seems to teleport slightly off center on when he teleports from the balcony where he starts the fight to when he teleports to the first side.

**Comment by gemt** [comment]
Fixed
