### ISSUE TITLE
Maexxna: Aggro Range needs to be increased

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#75]
# Scuba Cops PTR Test Feedback

### Issue - Aggro Range needs to be increased

**Evidence PTR vs Retail:**

https://youtu.be/Gur4D9iAKrs?t=9800 (PTR)
https://youtu.be/ECEJNlkZlt0?t=6 (Retail)

**Comment by gemt** [comment]
range increased slightly
