### ISSUE TITLE
Maexxna: Hit box needs to be slightly increased

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#76]
# Scuba Cops PTR Test Feedback

### Issue - Hit box needs to be slightly increased

**Evidence PTR vs Retail:**

https://youtu.be/d4RW9U-EBd4?t=102 (PTR)
https://youtu.be/ECEJNlkZlt0?t=36 (Retail)

**Comment by gemt** [comment]
Range increased slightly
