### ISSUE TITLE
Abomination Wing - Stitched Spewers should drop aggro

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#77]
These mobs did not seem to drop aggro when doing the "uppercut" ability.

How it should work: "Uppercut on primary target with deaggro component"

Source: http://wowwiki.wikia.com/wiki/Stitched_Spewer?oldid=309435

**Comment by gemt** [comment]
Fixed, though the description on wowwiki dosent make much sense as the spells its describing does not work/exist like described. The new changes should make sense though
