### ISSUE TITLE
Loatheb and Priest 8/8 T2

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#78]
Apparently the 8/8 T2 Priest set bonus didnt work on Loatheb. A greater heal didnt apply the renew like it should. Here's a short clip of our fight in which you can see Ratty aka "Rat" (with full T2) throw a Greater Heal on Ixl. On the left you can see the party frames, and no renew on Ixl after Ratty lands his heal. You can also check the combat log on the bottom right to find the "Rat's Greater Heal heals Ixl for 3134.".

Clip: https://www.youtube.com/watch?v=F-JPr4A1MjM

Proof: https://youtu.be/_hC1NYeBv18?t=74 (check combat log, she throws another GH at 2:35 in the video)

**Comment by gemt** [comment]
Fixed
