### ISSUE TITLE
Gate between Patchwerk and Grobbulus should be closed prior pw death

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#79]
Might be intended because of PTR, but I leave it here anyways.
[https://youtu.be/gtpxiJhcEOE?t=39s](https://youtu.be/gtpxiJhcEOE?t=39s)

**Comment by runklebc** [comment]
All doors were intentionally opened due to the 30 min boss timer, custom PTR fix, not triggering scripts to open doors.
