### ISSUE TITLE
Noth the Plaguebrigner: Evading/Reset when teleporting to balcony

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#80]
# Scuba Cops PTR Test Feedback

### Issue - Evading/Reset when teleporting to balcony
Fight also stops doing mechanics when this occurs. Waves of skeletons and warriors did not spawn after he evaded on the balcony. We tried this the first time with a typical kill with dots on the boss. Then a 2nd try again with putting 0 DoTs on Noth before he teleported and he still aggro'd to a player causing him to evade when he couldn't find a path to hit the player

**Evidence PTR vs Retail:**

https://youtu.be/pvyt75YKbu4?t=1261 (PTR)

(Literally any vanilla Noth video, obviously fight should not reset when he TP's)
https://www.youtube.com/watch?v=l9EFNnhelKI (Retail)
https://www.youtube.com/watch?v=u_HfJ01uyJw (Retail)

**Comment by gemt** [comment]
Should be fixed for next ptr session
