### ISSUE TITLE
Heigan the Unclean: After Heigan teleports to his platform the "Safety Dance" starts 3 seconds afterwards. "Safety Dance" should start 5 seconds after teleport.

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#81]
# Scuba Cops PTR Test Feedback

### Issue - After Heigan teleports to his platform the "Safety Dance" starts 3 seconds afterwards. "Safety Dance" should start 5 seconds after teleport.
The splashing of the green slime in phase2 (The "Safety Dance") is occurring 2 seconds too early. From the moment Heigan teleports to his platform there should be 5 seconds until the first splash happen. The current timer appears to be 3 seconds. This leaves people too little time to get to the first safe area resulting in many deaths.

**Evidence PTR vs Retail:**

https://youtu.be/pvyt75YKbu4?t=2561 (PTR - Heigan Teleport happens at 42:48, first splash happens at the 42:51/42:52 frame transition. ~3 second difference)

https://youtu.be/TbNMHq-C5Do?t=92 (Retail - Heigan Teleport happens at 1:42, first splash happens at 1:47/1:48 frame transition. ~5 second difference)
https://youtu.be/YDEwsOk6_ac?t=78 (Retail - Heigan Teleport happens at 1:23, first splash happens at 1:28. ~5 second difference)
https://www.youtube.com/watch?v=ZTZdCt60nQc (Retail - Heigan Teleport happens at 1:17, first splash happens at 1:21/1:22 frame transition. ~5 second difference)

**Comment by gemt** [comment]
It's currently 4 seconds (you can see that if you slow down your ptr video and see when the TP happens and when the first eruption happens, relative to the timers on the screen).

If you look at the timers bottomish-left on this video: https://www.youtube.com/watch?v=YDEwsOk6_ac&feature=youtu.be&t=78

it looks a lot like its closer to 4 than 5 seconds if you see when the boss appears on the platform opposed to what the timers say, and when the first eruption happens. 

In AFGM video you see the teleport has not visually happened until the "TP back" timer is on 43.5sec. The first eruption then happens on 38.8ish sec

Youtube timestamps become too inaccurate when its this short of a duration we're measuring, but onscreen addon timers for the players are perfect. 

I checked even more videos this way when the boss was scripted and i found, at least visually, it often happens closer to 4 than 5 seconds. The intended timer may have been 5 sec though. Not sure what's most accurate to do, I sortof like the 4 sec way, its still easy to get in possition in time if players do what Devlin from afgm does ;) I'm pretty sure the idea by Blizzard is its more or less too late to move after the teleport happens

**Comment by runklebc** [comment]
After looking back I think you may be correct about the 4 second thing. I'll close this ticket if it is already 4 seconds.
