### ISSUE TITLE
Sapphiron: Ice Block cast on players in air phase should not create more Ice Blocks on players hit by the Ice Block splash damage

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#82]
# Scuba Cops PTR Test Feedback

### Issue - Ice Block cast on players in air phase should not create more Ice Blocks on players hit by the Ice Block splash damage
- Players being hit by the "Ice Block" ability in phase 2 of Sapphiron should not create more Ice Blocks on nearby players. The player hit by Ice Block should only deal damage to nearby players instead.
- Sapphiron should Ice Block exactly 5 (https://github.com/elysium-project/naxxramas_ptr_feedback/issues/82#issuecomment-323410469) players in phase2.

**Evidence PTR vs Retail:**

https://youtu.be/pvyt75YKbu4?t=4797 (PTR)

**Forlorn Legacy** - All air phases time stamped:
https://youtu.be/iRW7EoVwmk0?t=88 (Retail - Forlorn Legacy)
https://youtu.be/iRW7EoVwmk0?t=175 (Retail - Forlorn Legacy)
https://youtu.be/iRW7EoVwmk0?t=274 (Retail - Forlorn Legacy)
https://youtu.be/iRW7EoVwmk0?t=382 (Retail - Forlorn Legacy)
https://youtu.be/iRW7EoVwmk0?t=479 (Retail - Folorn Legacy)

**A Few Good Men** - All air phases time stamped:
https://youtu.be/l9bW8Gxng0A?t=66 (Retail - A Few Good Men)
https://youtu.be/l9bW8Gxng0A?t=166 (Retail - A Few Good Men)
https://youtu.be/l9bW8Gxng0A?t=283 (Retail - A Few Good Men. **YOU CAN SEE ON THIS ONE THE RECORDING PLAYER IS WITHIN 5 YARDS OF OTHERS WHEN ICE BLOCKED AND THEY DO NOT GET ICE BLOCKED**)
https://youtu.be/l9bW8Gxng0A?t=324 (Retail - A Few Good Men)
https://youtu.be/l9bW8Gxng0A?t=416 (Retail - A Few Good Men)

**Momento Mori** - All air phases time stamped:
https://youtu.be/_SZdQd41O84?t=106 (Retail - Momento Mori)
https://youtu.be/_SZdQd41O84?t=203 (Retail - Momento Mori)
https://youtu.be/_SZdQd41O84?t=300 (Retail - Momento Mori)
https://youtu.be/_SZdQd41O84?t=497 (Retail - Momento Mori)
https://youtu.be/_SZdQd41O84?t=587 (Retail - Momento Mori)
https://youtu.be/_SZdQd41O84?t=677 (Retail - Momento Mori)

**Comment by gemt** [comment]
AFGM video where the mage  is changed by the rogue is probably the best proof that it should not spawn additional iceblocks, but at the same time I have this:

Slow down this video:
https://youtu.be/LfGiodElEqM?t=7m11s 
You can see the main target and the chained person at the above timestamp. 

After the bomb, when the iceblocks fade, its clearly the same two people that were hit above that get out of two different iceblocks at the following timestamp.
https://youtu.be/LfGiodElEqM?t=7m32s

Can't know for sure its just another block hitting the same player, but a fairly low chance that's the case ofc.

I have seen many airphases where there are only 4 iceblocks, including among those you link.

**Comment by runklebc** [comment]
I think there are too many videos out there where the maximum number of Ice Blocks is 4 or 5 to think otherwise. 

Including multiple people in Scuba that were in guilds like Nightmares Asylum in Vanilla retail that did Saph/KT when it was relevant report to us (anecdotally, but very strongly) that chaining never happened.

I think the rogue video is a perfect piece of evidence. I would imagine that you would see A LOT more videos of 6, 7, or 8 Ice Blocks if chaining happened in retail.

**Comment by gemt** [comment]
My assumption was always random 4-5.

Going with no chaining seems fair.

**Comment by runklebc** [comment]
Glad this was useful!

Let us know what bosses should be focused on next week for retesting or if we should test scourge invasion as well. Etc etc.

**Comment by kevmodrome** [comment]
Here is more evidence only one person per "bolt" gets turned into an ice block: https://youtu.be/rgrMtnzT8jw?t=1m36s

From what I can remember when playing back then you would always get 5 blocks unless the player hit by it died. Not 100% certain though.

**Comment by kevmodrome** [comment]
I have access to a dungeon guide printed in 2006. It says it's 5 ice blocks - less if people die. Here are some images:
Shows that it's actually vanilla wow: https://puu.sh/xdoVI/b95cd80105.jpg
Ice block info: https://puu.sh/xdoVv/b90bdaa921.jpg

If you need any information on boss abilities I can get you the information from it for you. Contact me on Discord (Myaka) with what you need.

**Comment by gemt** [comment]
Fixed on next PTR session
