### ISSUE TITLE
Kel'Thuzad: Chains of Kel'Thuzad should always target the current highest threat (Main Tank) and 4 random raid members.

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#83]
# Scuba Cops PTR Test Feedback

### Issue - Chains of Kel'Thuzad should always target the current highest threat (Main Tank) and 4 random raid members.
There was one instance where this did not happen. Forest was tanking KT when Mind Control happened and he did not get MC'd.

**Evidence PTR vs Retail:**

https://youtu.be/pvyt75YKbu4?t=6849 (PTR - Warlock POV)
https://www.twitch.tv/videos/167805870 (PTR - Tank/Effected Player POV, 1:50:44)

**Critical Mass** - All Mind Controls time stamped, in each instance the MT is ALWAYS Mind Controlled:
https://youtu.be/4jKlYVCAOcM?t=187 (Retail - Critical Mass)
https://youtu.be/4jKlYVCAOcM?t=246 (Retail - Critical Mass)
https://youtu.be/4jKlYVCAOcM?t=323 (Retail - Critical Mass)
https://youtu.be/4jKlYVCAOcM?t=416 (Retail - Critical Mass)
https://youtu.be/4jKlYVCAOcM?t=477 (Retail - Critical Mass)
https://youtu.be/4jKlYVCAOcM?t=589 (Retail - Critical Mass)

**Comment by smkrus** [comment]
KT MC should also be resetting the entire raid threat to 0 which didn't appear to happen.

**Comment by gemt** [comment]
Do you have any sources on that smkrus? My assumption was the threat was only reset for the players being MCed

**Comment by runklebc** [comment]
@gemt 

> Do you have any sources on that smkrus? My assumption was the threat was only reset for the players being MCed

Yes I do!

Nightmares Asylum kill video: 
https://www.youtube.com/watch?v=wSQtlvVebm0

Members of Scuba Cops were in this exact raid (Fahbulous & Darksicarii on Anathema), this was a week or two after the 2.0 patch but Naxx was obviously untouched as a raid.

Only 2 tanks are building threat on KT during this whole fight. 

Here is a time stamp of BOTH tanks being Mind Controlled at the same time and KT running around hitting fury warriors, rogues, etc until the Mind Controls break:

Starts @5:15
https://youtu.be/wSQtlvVebm0?t=308

If KT worked the way you are saying which is that only Mind Controlled targets get their threat wiped, which is incorrect, you would see KT continue to melee down the entire raid 1 by 1 until most members of the raid were dead after the Mind Controls break on both tanks. 

However you can clearly see @5:25:

https://youtu.be/wSQtlvVebm0?t=324

the Mind Controls end and KT goes back immediately to the tanks because the raid stops DPS for the most part and the two tanks use high instant threat abilities like Shield Slam, Heroic Strike, and Sunder Armor to retrieve aggro.

This definitively proves that ALL threat should be completely wiped at the beginning of the cast of "Chains of Kel'Thuzad".

**Comment by gemt** [comment]
It should now always MC MT + 4 random targets and reset threat
