### ISSUE TITLE
Kel'Thuzad: Players occasionally remain hostile to friendly raid members after Chains of Kel'Thuzad (Mind Control) has ended on them

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/naxxramas_ptr_feedback#84]
# Scuba Cops PTR Test Feedback

### Issue - Players occasionally remain hostile to friendly raid members after Chains of Kel'Thuzad (Mind Control) has ended on them

**Evidence PTR vs Retail:**

PTR:
This issue seems hard to replicate as we have multiple POV's where it doesn't happen:
https://www.twitch.tv/videos/167805856 (Warlock POV - 1:43:00 KT Fight)
https://youtu.be/pvyt75YKbu4?t=6381 (Rogue POV)

and multiple POV's where it does:
https://www.twitch.tv/videos/167805870 (Warrior Tank POV - No issues until KT dies, then 2 player are hostile after fight ends)
https://youtu.be/TXq_dqYmHzU?t=539 (Mage POV - Right at the end, player hostile dead on the ground)

Retail
https://www.youtube.com/watch?v=JFCvFepmQX0 (Retail - Nihilum vs Kel'Thuzad 40 man World First)
https://www.youtube.com/watch?v=O6D-uNCQgug (Retail - Holyfreaks vs. Kel'Thuzad Naxxramas 40 Vanilla)

**Comment by gemt** [comment]
This is the god old charm bug we have with our core and I'v been hoping someone else has the time to look at this. Its not related to KTs spell specifically, its the SPELL_AURA_AOE_CHARM effect, which is very bugged in our core. It's not just the hostility issue, but also that charmed players often don't properly attack other, non charmed, players.

**Comment by runklebc** [comment]
Yeah I was aware of that when I wrote this ticket, but I thought it should be opened to other developers could see it. It is a fairly rare occurrence but certainly something that should still be fixed in the long run. Naxx could certainly release without this fix given that it will be VERY difficult to reach KT in the 1st or even 2nd week with the difficultly of Saph with low Frost Resist.

**Comment by gemt** [comment]
Was fixed before naxx release.
