### ISSUE TITLE
Spider Wing - Wrong mob in spider pack

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#85]
The last spider pack before Anub'rekhan contains "Necro Stalker". This mob should be replaced by "Venom Stalker".
PTR: http://imgur.com/a/tF3SS
Retail: http://imgur.com/a/rCrRG 
https://youtu.be/cEsCSdp57d4?t=1m44s

**Comment by gemt** [comment]
Fixed
