### ISSUE TITLE
Kel'Thuzad: Chains of Kel'Thuzad (Mind Control) should wipe threat for all 40 members of the raid at the beginning of the cast.

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#86]
# Scuba Cops PTR Test Feedback

### Issue - Chains of Kel'Thuzad should wipe threat for all 40 members of the raid at the beginning of the cast.
This Issue is direct response to @gemt 's question on another ticket: https://github.com/elysium-project/naxxramas_ptr_feedback/issues/83#issuecomment-323455600

**Evidence PTR vs Retail:**

https://youtu.be/pvyt75YKbu4?t=6849 (PTR - Warlock)
https://www.twitch.tv/videos/167805870 (PTR - Tank)

**Nightmares Asylum** - 
https://www.youtube.com/watch?v=wSQtlvVebm0 (Retail - Nightmares Asylum)

Members of Scuba Cops were in this exact raid (Fahbulous & Darksicarii on Anathema), this was a week or two after the 2.0 patch but Naxx was obviously untouched as a raid.

Only 2 tanks are building threat on KT during this whole fight. 

Here is a time stamp of BOTH tanks being Mind Controlled at the same time and KT running around hitting fury warriors, rogues, etc until the Mind Controls break:

Starts @ 5:15:
https://youtu.be/wSQtlvVebm0?t=308

If KT worked the way you are saying which is that only Mind Controlled targets get their threat wiped, which is incorrect, you would see KT continue to melee down the entire raid 1 by 1 until most members of the raid were dead after the Mind Controls break on both tanks since they would be at 0 threat and the rest of the raid would have several minutes of threat built up over the course of the fight.

However you can clearly see @ 5:25:
https://youtu.be/wSQtlvVebm0?t=324

the Mind Controls end and KT goes back immediately to the tanks because the raid stops DPS for the most part and the two tanks use high instant threat abilities like Shield Slam, Heroic Strike, and Sunder Armor to retrieve aggro.

This definitively proves that ALL threat should be completely wiped from all 40 players at the beginning of the cast of "Chains of Kel'Thuzad".

**Comment by gemt** [comment]
Fixed
