### ISSUE TITLE
Gothik the Harvester: Add spawns CC vulnerabilities (Roots, Slows, Shackles, Fears)

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#87]
# Scuba Cops PTR Test Feedback

### Issue - Add spawns CC vulnerabilities

Trainee (Standard Humanoid Vulnerabilities): Fear, Shackle, Slow, Rooted, Polymorph https://youtu.be/CVqvIclhiqQ?t=145 (Fear example)
DKs (Standard Undead Vulnerabilities): Shackle, Slow, Rooted
Rider: Immune to everything

**Evidence PTR vs Retail:**
https://youtu.be/Gur4D9iAKrs?t=3294 (PTR)

**Curse** - 
https://www.youtube.com/watch?v=CVqvIclhiqQ (Retail)

**Comment by gemt** [comment]
Using these values now
