### ISSUE TITLE
Grobbulus only spawns one slime and injected players do not leave a cloud

### ISSUE THREAD

**Issue by Kamisayo** [elysium-project/naxxramas_ptr_feedback#88]
On the PTR, Grobbulus' Slime Spray only hits people in front of him (the main tank), meaning he only spawns one Fallout Slime. Furthermore, players affected by Mutating Injection do not leave a green cloud.

In every Grobbulus kill video from classic that I know of, melee DPS stand back to kill slimes and shoot at Grobbulus from range, since his Slime Spray is supposed to hit everybody AROUND him, meaning one slime should be spawned pr. melee in range. Videos also show that players affected by Mutating Injection will leave a cloud when cleansed.

I've found the following videos that support this:
https://www.youtube.com/watch?v=bJ5eJkujs7Y
https://www.youtube.com/watch?v=13rvgYl70fE
https://www.youtube.com/watch?v=L5q7jN4t9EA
https://www.youtube.com/watch?v=1d8BsGCkItQ (at 3:06 a warrior says "shooting arrows ftw, 799 crit”)
https://www.youtube.com/watch?v=qevwutWjSDs
https://www.youtube.com/watch?v=dOQXcBfwpaQ
https://www.youtube.com/watch?v=E1zZrldAz0A
https://www.youtube.com/watch?v=aHlmrKksF48 (PoV of a DPS warrior shooting his bow)
https://www.youtube.com/watch?v=uwiJLsMPvQ8
https://www.youtube.com/watch?v=egvkHLUUHkU
https://www.youtube.com/watch?v=tlCqQ5UjKHI (Rogue PoV)
https://www.youtube.com/watch?v=QmpRL-Y80Gw

While Wowwiki/Wowpedia in themselves are not definite sources, they fully support the strategy used by what seems to be every guild in classic. [Wowpedia states](https://wow.gamepedia.com/Grobbulus_(original)#Strategy):

"DPS on Grobbulus is ranged, so as to avoid spawning multiple fallout slimes. Only one slime should be spawned at a time(the MT's) which will presumably aggro onto a healer, and should otherwise be pulled to melee classes. They dispatch this slime, away from the ranged/healers, then return to adding ranged dps."

Currently on the PTR, Grobbulus only spawns one slime, even when 10+ melee DPS are on him, and injected players do not leave a cloud. The videos and strategy above document that these two mechanics should be changed.

**Comment by gemt** [comment]
The spell itself uses the target function TARGET_IN_FRONT_OF_CASTER, and has a 45yd range, so its impossible that its a 360 degrees spell, unless there is another spell which I have not yet found.

It's more likely in my mind that the reason many vanilla guilds had melee stay out was to avoid any fuckups where boss was turned just as he cast it, or melees were sucking and moving in front of the boss while the boss was moved.

**Comment by runklebc** [comment]
@Kamisayo - Gemt is correct, Grobbulus should only be targeting in a cone in front of him, similar to breaths that many Dragon type bosses have in WoW.

The injection dispel not creating a gas cloud has already been reported and fixed for next session according to Gemt.

This issue can probably be closed to leave room for other actual issues.

**Comment by Kamisayo** [comment]
You're probably right Gemt, particularly for the following reason:

Both the visual animation of slime spray as well as various descriptions of the ability indicate that it is a 180 degree frontal attack, and this coupled with poison clouds right behind the boss would mean there is no safe spot for melee, unless the tank keeps the boss at an angle towards the wall.

I can't quite tell from our PTR recordings if the spell does indeed hit 180 degrees in front of him, but most evidence suggests that this would be the correct function.
