### ISSUE TITLE
Loatheb: Should cast "Decurse" on himself once every 30 seconds removing any player casted curses on himself, "Decurse" timer beginning 5 seconds after Loatheb is engaged

### ISSUE THREAD

**Issue by runklebc** [elysium-project/naxxramas_ptr_feedback#89]
# Scuba Cops PTR Test Feedback

### Issue - Should cast "Decurse" on himself once every 30 seconds removing any player casted curses on himself, "Decurse" timer beginning 5 seconds after Loatheb is engaged.

- Curse of Agony
- Curse of Recklessness
- Curse of Elements
- Curse of Shadows
- Curse of Doom
- Curse of Tongues
- Curse of Weakness
- Vampiric Embrace

Loatheb is not currently casting this spell at all.

**Evidence PTR vs Retail:**
https://youtu.be/pvyt75YKbu4?t=3347 (PTR - You can clearly see all curses stay up 100% of the fight)

**Curse** - 
https://youtu.be/bMWKNeIISmo?t=60 (Retail - Engage happens at 1:00)
https://youtu.be/bMWKNeIISmo?t=91 (Retail - Watch from 1:31 to 1:35, both Curse of Shadows and Curse of Recklessness fall off at the EXACT same time. 5 seconds after pull + 30 seconds cast timer)
https://youtu.be/bMWKNeIISmo?t=122 (Retail - 2nd Decurse happens at 2:05, both Curse of Shadows and Curse of Recklessness fall off at the EXACT same time)
https://youtu.be/bMWKNeIISmo?t=151 (Retail - 3rd Decurse happens at 2:35, only Curse of Shadows is active this time, but is still removed)
https://youtu.be/bMWKNeIISmo?t=182 (Retail - 4th Decurse happens at 3:05, both Curse of Shadows and Curse of Recklessness fall off at the EXACT same time)
https://youtu.be/bMWKNeIISmo?t=214 (Retail - 5th Decurse happens at 3:35, only Curse of Shadows is active this time, but is still removed)

**Gentlemens Club** -
https://youtu.be/4gOCz_8K6Bc?t=25 (Retail - Engage happens at 0:25 seconds)
https://youtu.be/4gOCz_8K6Bc?t=58 (Retail - 1st Decurse happens at 1:00, 5 seconds after pull + 30 seconds cast timer, watch Curse of Elements)
https://youtu.be/4gOCz_8K6Bc?t=85 (Retail - 2nd Decurse happens at 1:30, watch Curse of Elements)
https://youtu.be/4gOCz_8K6Bc?t=116 (Retail - 3rd Decurse happens at 2:00, watch Curse of Elements)
https://youtu.be/4gOCz_8K6Bc?t=146 (Retail - 4th Decurse happens at 2:30, watch Curse of Elements)
https://youtu.be/4gOCz_8K6Bc?t=182 (Retail - 5th Decurse happens at 3:00, watch Curse of Elements)

**Comment by gemt** [comment]
Fixed. Will also instantly cast it if hit by Vamperic Embrace, as later fixed by blizzard in response to the D&T 5man kill. Poor spriests :(

**Comment by 30daystofixthings** [comment]
Vampiric Embrace should be usable on loatheb with the release of Naxx. Vampric Embrace was changed during the tbc pre-patch you can see tbc abilities such as vampric touch which is one of the main abilities that even allowed them to 5 man it.
