### ISSUE TITLE
Kel'Thuzad: Chains of Kel'Thuzad (Mind Control) should make players Immune from taking damage from Shadow Fissure

### ISSUE THREAD

**Issue by Forest-runklebc** [elysium-project/naxxramas_ptr_feedback#90]
# Scuba Cops PTR Test Feedback

### Issue - Chains of Kel'Thuzad (Mind Control) should make players Immune from taking damage from Shadow Fissure
-------------------------------------------------------------------------------------------------------------------
Big Edit: 
From the **Critical Mass** video below it looks like players should be Immune to Shadow  Fissure damage for 2-3 seconds after MC's end **IN ADDITION TO** being Immune during the Chains of Kel'Thuzad. The hunter is shrinking in size while running through the Shadow Fissure. This means that the MC is in the process of ending, but he still does NOT take any damage.

**Evidence PTR vs Retail:**

https://youtu.be/pvyt75YKbu4?t=6772 (PTR - Warlock POV, Slow the video down to 0.25 speed to see this happening better. Undertanker gets Mind Controlled right as a Shadow Fissure finishes its cast, instantly killing Undertanker, even though at the time he was Mind Controlled)
https://www.twitch.tv/videos/167805856 (PTR - Rogue POV, @ 1:49:42 Undertanker gets Mind Controlled right as a Shadow Fissure finishes its cast, instantly killing Undertanker, even though at the time he was Mind Controlled)

**Critical Mass** - This is the best video because the MC is completely inside the Shadow Fissure
https://youtu.be/4jKlYVCAOcM?t=614 (Retail - The hunter who is feared right in front of the priest making the video gets feared directly into a Shadow Fissure as it finishes casting and does not die)

**Holy Freaks** - 
https://youtu.be/O6D-uNCQgug?t=319 (Retail - Pig in melee range wanders into a Shadow Fissure right at the end of its cast, just on the edge)
https://youtu.be/O6D-uNCQgug?t=484 (Retail - 2 Pigs in melee range wander into a Shadow Fissure right at the end of its cast, just on the edge)

**Comment by gemt** [comment]
This is fixed for the duration of the mind control. However the "grace period" following after I have not figured out yet. I see 2 possibilities as to how it should be fixed.

1) There should be (but is currently missing in core) a general grace period from AOE after a creature charm ability ends.
2) There is a spell cast on players after the charm ends which gives immunity for a few seconds. I have not found any such spells that seem relevant to the encounter.
