### ISSUE TITLE
Four Horseman - Marks are partially resistible and spirits do not spawn on death

### ISSUE THREAD

**Issue by Kamisayo** [elysium-project/naxxramas_ptr_feedback#92]
On the PTR, you can partially resist the shadow damage done by the 4HM marks. Furthermore, the horsemen do not spawn their "spirit" on death, which is supposed to continue giving out marks.

Partial resist:
https://www.youtube.com/watch?v=IE-8l3UXtYI - Starting at 1:43, where his protection potion is removed, he takes a great number of marks throughout the rest of the video. He has at least 60 SR (from priest buff), but in spite of this does not fully or partially resist the damage from a _single_ mark the entire fight. Just as a counterexample, at 2:32 you can see him partially resist the meteor (fire) damage. It appears the marks should deal shadow damage but be tagged in the "physical" school (also supported by Wowpedia and various databases).

Spirits:
https://www.youtube.com/watch?v=r3ZprEL5hmE&feature=youtu.be&t=11m8s - you can see this mage running towards the spirit of Lady Blaumeux at 11:08, which applies a fourth mark to the player at 11:13.

This is further supported by each horseman having a spirit NPC whose ID is close to the actual horseman NPCs.
Mograine = 16062 - Mograine spirit = 16775
Blaumeux - 16065 - Blaumeux spirit = 16776
Zeliek = 16063 - Zeliek spirit = 16777
Korth'azz = 16064 - Korth'azz spirit = 16778

**Comment by runklebc** [comment]
Scuba Cops Killing 4Horse on PTR: 

Pause the video exactly at 1:58:47, you can see the Spirit of Mograine in the corner.

Screen Shot: [asdf](http://i.imgur.com/GcAT69Z.png)
YouTube time stamp: https://youtu.be/Gur4D9iAKrs?t=7127

**Comment by gemt** [comment]
It works, but not when the bosses are manually spawned which it was for some guilds due to the 30min timer thing.
