### ISSUE TITLE
Kel'Thuzad: Frostbolt-Volley

### ISSUE THREAD

**Issue by R4k3te** [elysium-project/naxxramas_ptr_feedback#94]
In additon to casting (interruptable) Frostbolts on the highest target on his threat list, Kel'Thuzad should also be using his AoE Frostbolt-Volley ability.

Looking at this VoD from the Naxx PTR he is currently not using this at all.
https://youtu.be/pvyt75YKbu4?t=1h52m3s

Proof of what he should be doing:
https://www.youtube.com/watch?v=SMHQJs-uqfU
At 0:26 in the video he does his Frostbolt volley, followed by a single target Frostbolt on the mage highest on threat after the MT had just died.

**Comment by gemt** [comment]
It should have worked, but some changes have been made for next PTR session, will see then.

**Comment by R4k3te** [comment]
He should use his volley ~every 30sec.

**Comment by smkrus** [comment]
Volley should actually be every 15 seconds.

**Comment by gemt** [comment]
Fixed
