### ISSUE TITLE
Sapphiron: Blizzards

### ISSUE THREAD

**Issue by R4k3te** [elysium-project/naxxramas_ptr_feedback#95]
From what i can tell the Blizzards in the Sapphiron encounter are not yet working as intended. Currently there are to few blizzards spawning and they remain in one location. Instead they should be slowly moving and following players around.
Current implementation of Sapphirons blizzards can be seen here:
https://youtu.be/pvyt75YKbu4?t=1h27m

Proof of moving blizzards in vanilla:
https://youtu.be/DBY1vqfID0A?t=2m9s

**Comment by gemt** [comment]
In the video you linked they _are_ moving. 
I will re-check the spawn frequency

**Comment by R4k3te** [comment]
They are deffinately not moving fast enough then.
