### ISSUE TITLE
Abomination Wing - Embalming Slime aggro radius

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#96]
Back on retail these had a large aggro radius.
On PTR they seem to have a aggro radius of approx 20 yards.
I dont have any exact number but Im sure it should be increased. 40?
> It is important to note that the aggro radius is quite large. Once you are in the room and have them dead, get to the next room and make sure people stay very far away from the little slimes.
https://wow.gamepedia.com/index.php?title=Embalming_Slime&oldid=240666
https://youtu.be/Bybgi4kxvHg?t=1m22s

**Comment by gemt** [comment]
Fixed
