### ISSUE TITLE
Four Horsemen Aggro Range seems to be wrong.

### ISSUE THREAD

**Issue by kevmodrome** [elysium-project/naxxramas_ptr_feedback#97]
Looking at old videos and from remembering the fight you were not able to get as close to the boss as you can on this or other private servers. Here's how close you can get on the PTR: http://imgur.com/gqDJGLB
The point of aggro should be around where Schoosby is: https://www.youtube.com/watch?v=Gur4D9iAKrs&t=6003s

Looking at this video you can approximately see the range on the aggro: https://youtu.be/sljVITJREd8?t=1m54s - shows how you can both stand in the corner and how huge the aggro range is.

**Comment by runklebc** [comment]
You're correct that the aggro range WHEN THEY CAN SEE YOU should be longer, but if you approach out of line of sight they should not aggro.

This was a popular strat in retail to be able to get your tanks up closer to the bosses.

**Comment by kevmodrome** [comment]
That's interesting, I never saw any guild use that strategy, I've been trying to find videos showing it off but I have not been successful. Can you show me a source?

**Comment by gemt** [comment]
Would like to see a video of it too. In all videos iv seen the pull happens just about on the corner you'd have to get around to approach closer out of line of sight. From those videos it does not even look possible to get there without pulling unless invis pot

**Comment by runklebc** [comment]
Here you go, proof that you can LoS the 4 Horseman on the pull as opposed to aggroing them from 50 yards like a lot of guilds did:

Forlorn Legacy 4 Horseman Vanilla:

https://youtu.be/Mi-otCkSKdk?t=91

Screen shot at that exact time stamp for simplicity: http://i.imgur.com/J2MxQCV.png

**Comment by kevmodrome** [comment]
Perfect! Closing.

**Comment by gemt** [comment]
Would still be interesting to know if you can just waltz up to behind los, or if you actually have to use an invis pot to get around the corner left or right side to get out  of los.

**Comment by Forest-runklebc** [comment]
You can just walk up, no invis pot. Like I said in other tickets, we have guildies that did this in retail that suggested the tanks walk up like that specifically because that's how their guild pulled 4H in Vanilla.

Most guilds don't show their 4H pull, typically the videos start mid pull.

The above screen shot / video should be plenty evidence for being able to LoS and walk up at a specific angle.

**Comment by kevmodrome** [comment]
None of these videos show them getting there though which was what Gemt was asking about. Also, no need to use caps and make everything bold - your text is perfectly readable without it.

**Comment by Forest-runklebc** [comment]
Worked with Gemt today on the PTR for a minute in combination with a couple videos of where exactly the 4H aggro radius should be.

You will be able to hug the wall to get into LoS position behind the pillars before pulling.

**Comment by ettern** [comment]
I dont really see why Forest have to prove anything regarding the starting position (atleast here on Github). The video by Noir should be enough evidence that it should be possible. Now its up you (you're guild) to get to that position.
