### ISSUE TITLE
Naxxramas Armor/Resistance values

### ISSUE THREAD

**Issue by gemt** [elysium-project/naxxramas_ptr_feedback#98]
Currently the majority of Naxxramas trash and bosses use the default, level based, armor values, and generally have little or not resistances.

I know armor varies slightly on some bosses, but i currently have no idea where to find info on what each boss and trashmob should have as armor/resist value.

Looking for any input on this topic.

**Comment by runklebc** [comment]
Maexnna should be your baseline for bosses at the very least. There is 100% hard evidence from vanilla where this hunter checked Beast Lore.

http://www.kurai.com/wow/naxx/maexxna.jpg

Slightly higher for tank bosses like Thaddius/Patchwerk. Lower for caster bosses?

**Comment by gemt** [comment]
3700 is extremely low in our core, the default is 4691, Ragnaros has 5691, we all know how AQ was for a long time. Most non-modified bosses have 4691. 

I seem to recall an EJ post about boss armor values in naxx, but hard to find on webarchive after EJ went rip.

**Comment by Skarseth** [comment]
https://github.com/elysium-project/server/issues/677 relevant
