### ISSUE TITLE
Four Horsemen - Lady Blaumeux' void zone damage

### ISSUE THREAD

**Issue by ettern** [elysium-project/naxxramas_ptr_feedback#99]
During our PTR testing I noticed something that might be a bug.
I specific tested the void zone damage by standing in it a couple of times. Out of 6 void zone ticks, 5 of them 75% partially resisted, meaning I took about 1000 damage instead of 4000 damage per tick.
Yes I know, I might just been lucky..
But, I've been looking through some of the other recordings from PTR, and from what I can see you take 75% partially resisted damage almost all the time.
Below you can find some retail videos when void zone damage is taken.

Additionally it seems that after the void zone is placed on the ground, it takes longer time before the first tick takes place, compared to retail.
From my calculation based on retail videos, the void zone damage works like this; Void Zone placed on ground -> 1 second -> 1st tick -> 0.5 second -> 2nd tick -> 0.5 second -> 3rd tick and so on...

https://youtu.be/hGewOCCa1_A?t=21m31s
https://youtu.be/JUTIikVDjJk?t=9m37s
https://youtu.be/JUTIikVDjJk?t=6m49s
https://youtu.be/JUTIikVDjJk?t=2m12s
https://youtu.be/YM2rIrBTpzE?t=6m59s
https://youtu.be/YM2rIrBTpzE?t=4m41s
https://youtu.be/8rC4Pibrt1Q?t=5m36s
https://youtu.be/IE-8l3UXtYI?t=3m7s

**Comment by gemt** [comment]
Fixed
